# Generated by Django 4.2 on 2026-02-02 03:39

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_job_options"),
    ]

    operations = [
        VectorExtension(),
    ]
